FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
ENV GOTOOLCHAIN=auto
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /{{ .NodeID }} ./cmd/{{ .NodeID }}

FROM gcr.io/distroless/static-debian12
COPY --from=builder /{{ .NodeID }} /{{ .NodeID }}
EXPOSE 8080
ENTRYPOINT ["/{{ .NodeID }}"]
